server:
  port: 8089
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

spring.datasource:
    url: jdbc:mysql://127.0.0.1:3306/dc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: dc
    password: uat123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
